### ISSUE TITLE
Discuss missing API features

### ISSUE THREAD

**Issue by LukasBombach** [LukasBombach/de1#20]
Yay or nay, should we add `async de1.getTemperature(): Promise<number>`?

**Comment by oscar-b** [comment]
1. Which temperature, aren't there several? The headTemp one ("metal" I think) switches between measuring water temp during a shot, or something like that. Needs to be investigated using the original source.

2. What's the alternative way to get the temp? By subscribing to events? You can't access `machine.read()` directly?

I guess there are other infos that should be accessible as well, or the idea is to only expose them by events?

**Comment by LukasBombach** [comment]
> 1. Which temperature, aren't there several? The headTemp one ("metal" I think) switches between measuring water temp during a shot, or something like that. Needs to be investigated using the original source.

Oh that's right! But I was aiming for a high level API, i.e.

```ts
de1.getMixTemp();
de1.getHeadTemp();
de1.getSteamTemp();
```

but maybe that is not a good idea. What's your opinion on this?

> 2. What's the alternative way to get the temp? By subscribing to events?

I'd definitely like to be able to do both, the one use-case being when you want to read the current temp and do something, and the other one would be when you monitor the temp.

> You can't access `machine.read()` directly?

If there's a use-case for that... my initial thought was to have that API as stated above, but that's open for discussion.

> I guess there are other infos that should be accessible as well, or the idea is to only expose them by events?

My idea was to give a direct top level API for all common use-cases. I'd rather have a long list of functions than a nested or indirect way of retrieving things

**Comment by oscar-b** [comment]
> My idea was to give a direct top level API for all common use-cases. I'd rather have a long list of functions than a nested or indirect way of retrieving things

That's fine, I think. The alternative would be `de1.machine.read('shot').headTemp` or similar, and yeah that's a bit clunky.

**Comment by oscar-b** [comment]
And absolutely, both direct reading and event subscription has their use cases, let's have both.

**Comment by LukasBombach** [comment]
Yes. And we might want to have one `read()` and `write()` (or maybe  `get()` / `set()`) as additional methods for random low-level access for other developers for the times we don't fit their needs

**Comment by LukasBombach** [comment]
I propose the following API additions:

```ts
de1.getMixTemp();
de1.getHeadTemp();
de1.getSteamTemp();
de1.getShotSettings();
de1.setShotSettings();
de1.getVersions();
de1.get(name: ConverterName);
de1.set(name: ConverterName, value: ConverterValue);
```

if (or rather when) we see that this API isn't enough or designed badly or whatever we just change it in the future releases, I guess we'll just see when we implement the app and eat our own dog food etc

**Comment by oscar-b** [comment]
Yeah agreed, let's just implement something and see how far it gets us 👍

**Comment by LukasBombach** [comment]
ok cool
