### ISSUE TITLE
Rename "prettier" task to "lint"

### ISSUE THREAD

**Issue by LukasBombach** [LukasBombach/de1#30]
The `prettier` task in 

https://github.com/LukasBombach/de1/blob/4fa0230e540efa6c497dca9e3dc0f183b8bc0774/package.json#L12

is actually a task that lints the code, so it should be called `lint`

**Comment by oscar-b** [comment]
Don’t agree, linting is done by something like eslint.. prettier is purely aesthetic. If it should be a bit more general, “style” / “check-style” / “styling” perhaps?

**Comment by LukasBombach** [comment]
You're absolutely right, I did not think of the stuff that prettier does not do. Just disregard this issue
